
image: node:16
stages:
  - test_build_backend
  - deploy_backend
  - test_build_frontend
  - deploy_frontend
cache:
  paths:
    - node_modules/
    - backend/node_modules
    - frontend/node_modules

#Verify that our backend server will build properly
build_backend:
  stage: test_build_backend
    # Map our environment variables.
  script:
    - |
      cd backend
      yarn
      yarn build

deploy_backend:
  stage: deploy_backend
  only:
    - staging
  before_script:
    - apt-get -y update
    - apt-get -y install openssh-server
    - cd ~
    - mkdir -m 0700 ~/.ssh
    - ssh-keyscan -H tn.enxo.co -p 8202 > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - cat $PRIVATE_KEY_FILE > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Starting deploy"
    - cd $CI_PROJECT_DIR/backend
    - yarn 
    - yarn build
    - rsync -avz $CI_PROJECT_DIR/backend/build murph@SSH_HOST:/home/murph/mono-repo-staging/backend
    # - ssh -p $SSH_PORT murph@$SSH_HOST 'bash -s' < $CI_PROJECT_DIR/deploy.sh
    - echo "Deployment successful"
  
#Verify that our backend server will build properly
build_frontend:
  stage: test_build_frontend
  script:
    - |
      cd frontend
      yarn
      yarn build

deploy_frontend:
  stage: deploy_frontend
  only:
    - staging
  before_script:
    - apt-get -y update
    - apt-get -y install openssh-server
    - cd ~
    - mkdir -m 0700 ~/.ssh
    - ssh-keyscan -H tn.enxo.co -p 8202 > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - cat $PRIVATE_KEY_FILE > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Starting deploy"
    - rsync -avz $CI_PROJECT_DIR/frontend/build murph@SSH_HOST:/home/murph/mono-repo-staging/frontend
    - rsync -avz $CI_PROJECT_DIR/frontend/frontend-php murph@SSH_HOST:/home/murph/mono-repo-staging/php
    # - ssh -p $SSH_PORT murph@$SSH_HOST 'bash -s' < $CI_PROJECT_DIR/frontend_deploy.sh
    - echo "Deployment successful"
  