# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:16

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
services:
  # - mysql:latest
  # - redis:latest
  # - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/
    - backend/node_modules
    - frontend/node_modules

# test_async:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/async.spec.js

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js

# Build our backend api server and push it to production
build_backend:
    variables:
      PORT: PORT
      SESSION_SECRET: SESSION_SECRET
      DOMAIN: https://portal.hhlearning.com
      DB_CONNECTION_STRING: DB_CONNECTION_STRING
      NODE_ENV: production
      MAIL_FROM_ADDRESS: MAIL_FROM_ADDRESS
      MAIL_FROM_DOMAIN: hhlearning.com
      POSTMARK_API_KEY: POSTMARK_API_KEY
      REACT_APP_SALT: REACT_APP_SALT
      ADMIN_TOKEN: ADMIN_TOKEN
    script:
        - |
          cd backend
          yarn
          yarn build
          scp -P$SSH_PORT -r * $SSH_USER@$SSH_HOST:/home/murph/mono-repo-staging/

