version: '3'

services: 
    database:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: hilger
        ports:
            - 5432:5432
    app:
        build:
            context: ./backend
            target: dev
            dockerfile: Dockerfile.backend
        restart: on-failure
        ports:
            - 3000:3000
        volumes:
            - ./backend/src:/app/src
            - ./backend/keystone.ts:/app/keystone.ts
            - ./backend/.keystone:/app/.keystone
            - ./backend/schema.graphql:/app/schema.graphql
            - ./backend/schema.prisma:/app/schema.prisma
            - ./backend/auth.ts:/app/auth.ts
            - ./backend/schema.ts:/app/schema.ts
            - ./backend/schema:/app/schema
            - ./backend/.env:/app/.env
            - ./backend/.env.example:/app/.env.example
            - ./backend/migrations:/app/migrations
    adminer:
        image: adminer
        ports:
            - 8080:8080
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        restart: on-failure
        ports: 
            - 4000:3000
        command: yarn start



