version: '3.8'

services: 
    database:
        image: postgres:latest
        volumes:
            - postgres_volume:/var/lib/postgresql/data
            - ./dockerConfig:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: hilger
        ports:
            - 5432:5432
        networks:
            - hilger
    app:
        container_name: app
        build:
            context: ./backend
            target: dev
            dockerfile: Dockerfile.backend
        restart: on-failure
        ports:
            - $PORT:$PORT
        networks:
            - hilger
        volumes:
            - ./backend/src:/app/src
            - ./backend/keystone.ts:/app/keystone.ts
            - ./backend/.keystone:/app/.keystone
            - ./backend/schema.graphql:/app/schema.graphql
            - ./backend/schema.prisma:/app/schema.prisma
            - ./backend/auth.ts:/app/auth.ts
            - ./backend/schema.ts:/app/schema.ts
            - ./backend/schema:/app/schema
            - ./backend/routes:/app/routes
            - ./.env:/app/.env
            - ./.env.example:/app/.env.example
            - ./backend/migrations:/app/migrations
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - hilger
    frontend:
        container_name: frontend
        restart: on-failure
        depends_on:
            - app
        build:
            context: ./frontend
            target: dependencies
        volumes:
            - ./frontend:/home/node/app
            - nodeMod:/home/node/frontend/node_modules
        ports: 
            - 4000:3000
            - 3010:3010
        networks:
            - hilger
        command: yarn dev
        environment:
            - DANGEROUSLY_DISABLE_HOST_CHECK=true
            - HOST=0.0.0.0
    proxy:
        container_name: proxy
        build: 
            context: .
            dockerfile: Dockerfile.proxy
        ports:
            - 8081:8080
        networks:
            - hilger
        volumes:
            - ./dockerConfig/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend-php/:/var/www/html/
            - .env:/var/www/html/
    mailcatcher:
        image:  schickling/mailcatcher
        ports:
            - 1080:1080
volumes:
    postgres_volume:
    nodeMod:
networks:
    hilger:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1