version: '3'

services: 
    database:
        image: postgres:latest
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: hilger
        ports:
            - 5432:5432
        networks:
            - hilger
    app:
        build:
            context: ./backend
            target: dev
            dockerfile: Dockerfile.backend
        restart: on-failure
        ports:
            - $PORT:$PORT
        networks:
            - hilger
        volumes:
            - ./backend/src:/app/src
            - ./backend/keystone.ts:/app/keystone.ts
            - ./backend/.keystone:/app/.keystone
            - ./backend/schema.graphql:/app/schema.graphql
            - ./backend/schema.prisma:/app/schema.prisma
            - ./backend/auth.ts:/app/auth.ts
            - ./backend/schema.ts:/app/schema.ts
            - ./backend/schema:/app/schema
            - ./.env:/app/.env
            - ./.env.example:/app/.env.example
            - ./backend/migrations:/app/migrations
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - hilger
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        restart: on-failure
        volumes:
            - ./frontend/.env:/app/.env
            - ./frontend:/app
        ports: 
            - 4000:3000
        networks:
            - hilger
        command: yarn start
        environment:
            - DANGEROUSLY_DISABLE_HOST_CHECK=true
            - HOST=0.0.0.0
    proxy:
        build: 
            context: .
            dockerfile: Dockerfile.proxy
        ports:
            - 8081:8080
        networks:
            - hilger
        volumes:
            - ./dockerConfig/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend-php/font:/var/www/html/font
            - ./frontend-php/makefont:/var/www/html/makefont
            - ./frontend-php/parents:/var/www/html/parents
            - ./frontend-php/static:/var/www/html/static
            - ./frontend-php/db-config.php:/var/www/html/db-config.php
            - ./frontend-php/fpdf.php:/var/www/html/fpdf.php
            - ./frontend-php/print.php:/var/www/html/print.php
    mailcatcher:
        image:  schickling/mailcatcher
        ports:
            - 1080:1080
volumes:
    postgres_volume:
networks:
    hilger:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1